### ISSUE TITLE
Unable to run with uvloop

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [xnuinside/gino-admin#37]
Hey there! This is shaping up to be super useful for me. Thanks for your hard work!

I tried to add this to my Sanic app and then to start it up with uvloop. It gives me an error because `gino_admin.core.add_admin_panel` tries to run it's own asyncio loop. I noticed that the function that it calls doesn't seem to have any async components. Would you accept a patch to remove the asyncio call and change `gino_admin.users.add_users_model` to a synchronous function?

**Comment by xnuinside** [comment]
@rafmagns-skepa-dreag , hi! Interesting that I did not reproduce this error and this is why I did not catch it :/ but I understand the reason. Yes, I will update code and remove it.

**Comment by xnuinside** [comment]
@rafmagns-skepa-dreag  please test version 0.2.4, I released the fix

**Comment by rafmagns-skepa-dreag** [comment]
works great. Thanks!
