### ISSUE TITLE
Customize add/edit page

### ISSUE THREAD

**Issue by nmzgnv** [xnuinside/gino-admin#44]
How can I customize the edit page? Id field available for editing, no default values for fields. 
Lib version:  0.2.5

Simple model:
```
class User(db.Model):
    __tablename__ = 'users'

    pk = Column(db.String(), primary_key=True, unique=True)

    telegram_id = Column(Integer())
    nickname = Column(String(length=33), default='-')

    def __str__(self):
        return f'{self.nickname} - {self.telegram_id}'
```
![image](https://user-images.githubusercontent.com/46592780/147381742-a48964f8-40ea-4048-84ac-e52df679e498.png)

**Comment by nmzgnv** [comment]
Is it available to hide field?

**Comment by xnuinside** [comment]
@nmzgnv  hi, I did not update library a long time - it's not available now, but it's easy to add, I can add to config some field like 'hide_columns' that expect list of Model.column_name that will be hided. It is will be ok? I can add it quickly.

**Comment by nmzgnv** [comment]
@xnuinside It will be great, I can help :0

**Comment by xnuinside** [comment]
added in version gino-admin==0.3.0 (already released)

https://github.com/xnuinside/gino-admin/blob/master/CHANGELOG.txt#L3 - description

& sample - https://github.com/xnuinside/gino-admin/blob/master/examples/base_example/src/app.py#L52

**Comment by xnuinside** [comment]
@nmzgnv  if needed something more - feel free to open new issue or PR
